version: '2.2'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elastic
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

   mongo:
     image: mongo
     container_name: mongo
     restart: always
   	
volumes:
  esdata:

